%Created by Yuren Chen, 2021/03/18
%Read the files generated by GCE_DATA_TOOLBOX.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
r_dir = 'C:\Users\cheny\Desktop\EcoHAB\USGS_River\';
r(1) = load([r_dir,'USGS_02324000_STEINHATCHEE.mat']);
r(2) = load([r_dir,'USGS_02323500_SUWANNEE.mat']);
r(3) = load([r_dir,'USGS_02313250_WITHLACOOCHEE.mat']);
r(4) = load([r_dir,'USGS_02304500_HILLSBOROUGH.mat']);
r(5) = load([r_dir,'USGS_02301500_ALAFIA.mat']);
r(6) = load([r_dir,'USGS_02300500_LITTLE_MANATEE.mat']);
r(7) = load([r_dir,'USGS_02299950_MANATEE.mat']);
r(8) = load([r_dir,'USGS_02298880_MYAKKA.mat']);
r(9) = load([r_dir,'USGS_02296750_PEACE.mat']);
r(10) = load([r_dir,'USGS_02292900_CALOOSAHATCHEE.mat']);
r(11) = load([r_dir,'USGS_02307498_LAKE_TARPON.mat']);
r(12) = load([r_dir,'USGS_02306647_SWEETWATER_CREEK.mat']);
r(13) = load([r_dir,'USGS_02307000_ROCKY_CREEK.mat']);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
river_flow0 = get_nwis_timeseries(r,out_date,'Mean river discharge');
river_flow = river_flow0(1:11,:);
river_flow(11,:) = sum(river_flow0(11:13,:),1);


% river_temp = get_nwis_timeseries(r,out_date,'Mean water temperature');
% river_temp(1:4,:) = repmat(river_temp(5,:),4,1);
% river_temp(6:9,:) = repmat(river_temp(10,:),4,1);

t_dir = 'C:\Users\cheny\Desktop\EcoHAB\Water_Atlas\';
t = load([t_dir,strcat('WA_',num2str(year),'.mat')]);
t_dat = t.temp_dat;
t_m = t.temp_mean;

for i=1:11
    t_min = min(t_dat{i}(:,1));
    t_max = max(t_dat{i}(:,1));
    if(out_date(1)>=t_min&&out_date(end)<=t_max)
        river_temp(i,:) = interp1(t_dat{i}(:,1),t_dat{i}(:,2),out_date);
    else
        tmp = interp1(0:365,t_m{i}(:,2),out_date-out_date(1));
        tmp(isnan(tmp)) = interp1(0:365,t_m{i}(:,2),out_date(isnan(tmp))-out_date(1),'nearest','extrap');
        river_temp(i,:) = tmp;
    end
end

t_dat = t.sal_dat;
t_m = t.sal_mean;
for i=1:11
    if(~isempty(t_dat{i}))
        t_min = min(t_dat{i}(:,1));
        t_max = max(t_dat{i}(:,1));
        if(out_date(1)>=t_min&&out_date(end)<=t_max)
            river_salt(i,:) = interp1(t_dat{i}(:,1),t_dat{i}(:,2),out_date);
        else
            tmp = interp1(0:365,t_m{i}(:,2),out_date-out_date(1));
            tmp(isnan(tmp)) = interp1(0:365,t_m{i}(:,2),out_date(isnan(tmp))-out_date(1),'nearest','extrap');
            river_salt(i,:) = tmp;
        end
    else
        river_salt(i,:) = zeros(size(out_date));
    end
end

if(isfield(t,'tss_dat'))
    t_dat = t.tss_dat;
    t_m = t.tss_mean;
    for i=1:11
        if(~isempty(t_dat{i}))
            t_min = min(t_dat{i}(:,1));
            t_max = max(t_dat{i}(:,1));
            if(out_date(1)>=t_min&&out_date(end)<=t_max)
                river_tss(i,:) = interp1(t_dat{i}(:,1),t_dat{i}(:,2),out_date);
            else
                tmp = interp1(0:365,t_m{i}(:,2),out_date-out_date(1));
                tmp(isnan(tmp)) = interp1(0:365,t_m{i}(:,2),out_date(isnan(tmp))-out_date(1),'nearest','extrap');
                river_tss(i,:) = tmp;
            end
        else
            river_tss(i,:) = zeros(size(out_date));
        end
    end
end

river_flow([1:7 9:10],:) = river_flow([1:7 9:10],:).*-1;

    
    